# Generated by Django 6.0.1 on 2026-01-30 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0002_rename_cricket_cricketdetalis_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cricketdept',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cricketapp.coach'),
        ),
    ]
