# Generated by Django 6.0.1 on 2026-02-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketapp', '0003_coach_cricketdept_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketdetalis',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
