# Generated by Django 6.0 on 2025-12-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('gts', models.FloatField()),
                ('online', models.CharField(max_length=30)),
            ],
        ),
    ]
