# Generated by Django 6.0 on 2025-12-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gts',
            new_name='gst',
        ),
    ]
