# Generated by Django 5.2.8 on 2025-12-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.IntegerField()),
                ('image', models.ImageField(default='test.png', upload_to='image')),
            ],
        ),
    ]
