# Generated by Django 6.0.2 on 2026-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('dept', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
            ],
        ),
    ]
