# Generated by Django 5.2.8 on 2025-12-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=20)),
                ('e_age', models.PositiveIntegerField()),
                ('e_salary', models.PositiveIntegerField()),
                ('e_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
