# Generated by Django 6.0.3 on 2026-03-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_order_address_remove_order_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
