# Generated by Django 5.2.8 on 2026-01-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decs',
            new_name='desc',
        ),
    ]
