# Generated by Django 5.2.8 on 2026-01-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0006_bils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bils',
            name='note',
        ),
    ]
