# Generated by Django 5.2.8 on 2026-01-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0007_remove_bils_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='bils',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshopapp.order'),
        ),
    ]
