# Generated by Django 6.0.2 on 2026-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_employee_age_alter_employee_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='test.png', null=True, upload_to='image'),
        ),
    ]
