# Generated by Django 5.2.8 on 2026-02-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_oredrdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='patid',
            new_name='payid',
        ),
    ]
