# Generated by Django 6.0 on 2025-12-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('veg', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('gst', models.FloatField()),
                ('rating', models.CharField(max_length=30)),
            ],
        ),
    ]
