# Generated by Django 6.0.2 on 2026-03-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
