# Generated by Django 6.0.3 on 2026-03-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
