# Generated by Django 6.0.3 on 2026-03-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_address_alter_orderdetalis_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
