# Generated by Django 6.0.3 on 2026-03-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_order_address_order_fullname_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
