# Generated by Django 5.2.8 on 2026-01-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0004_order_orderdetils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetils',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalis', to='eshopapp.order'),
        ),
    ]
