# Generated by Django 5.2.8 on 2026-01-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0005_alter_orderdetils_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
