# Generated by Django 6.0.3 on 2026-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_website_contact_webiste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='webiste',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
