# Generated by Django 6.0.3 on 2026-03-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_contact_webiste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='webiste',
        ),
    ]
