# Generated by Django 6.0 on 2025-12-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('fromate', models.CharField(max_length=50)),
                ('run', models.IntegerField()),
                ('con', models.IntegerField()),
                ('score', models.IntegerField()),
                ('avg', models.FloatField()),
                ('four', models.IntegerField()),
                ('six', models.IntegerField()),
            ],
        ),
    ]
