# Generated by Django 6.0 on 2025-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='jenil.png', upload_to='image'),
        ),
    ]
