# Generated by Django 6.0.3 on 2026-04-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('age', models.IntegerField()),
                ('image', models.ImageField(default='test.png', upload_to='image')),
            ],
        ),
    ]
