# Generated by Django 6.0.3 on 2026-04-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employes',
            name='image',
        ),
    ]
